### ISSUE TITLE
bert_pretrain里的vocab.txt如何生成

### ISSUE THREAD

**Issue by Joe-zsc** [shawroad/NLP_pytorch_project#30]

**Comment by shawroad** [comment]
这里的词表是bert自带的呀。 如果你要加载bert的预训练，你肯定也要用配套的词表。

**Comment by Joe-zsc** [comment]
> 这里的词表是bert自带的呀。 如果你要加载bert的预训练，你肯定也要用配套的词表。
请问如何用自己的语料库生成vocab.txt呢，因为我用bert_pretrain里的vocab.txt的时候，发现assert len(tags[i]) == len(sentences[i])（data_loader.py第54行）出错，调试发现tokens = self.tokenizer.tokenize这里分词与预想的不一样

**Comment by shawroad** [comment]
> > 这里的词表是bert自带的呀。 如果你要加载bert的预训练，你肯定也要用配套的词表。
> > 请问如何用自己的语料库生成vocab.txt呢，因为我用bert_pretrain里的vocab.txt的时候，发现assert len(tags[i]) == len(sentences[i])（data_loader.py第54行）出错，调试发现tokens = self.tokenizer.tokenize这里分词与预想的不一样

这里不是词表的问题，是因为你的标签和我的标签不一样。也就是标注的起始结束等等之类的标签不同。 跟bert的词表没有任何关系。

**Comment by Joe-zsc** [comment]
> > > 这里的词表是bert自带的呀。 如果你要加载bert的预训练，你肯定也要用配套的词表。
> > > 请问如何用自己的语料库生成vocab.txt呢，因为我用bert_pretrain里的vocab.txt的时候，发现assert len(tags[i]) == len(sentences[i])（data_loader.py第54行）出错，调试发现tokens = self.tokenizer.tokenize这里分词与预想的不一样
> 
> 这里不是词表的问题，是因为你的标签和我的标签不一样。也就是标注的起始结束等等之类的标签不同。 跟bert的词表没有任何关系。

会不会是因为我的语料是英文的呢，您有英文的词表吗

**Comment by Joe-zsc** [comment]
BERT-Large, Cased：L=24, H=1024, A=16, 总参数=340M：
https://storage.googleapis.com/bert_models/2018_10_18/cased_L-12_H-768_A-12.zip

英文的bert预训练语料库可以从这里下载

**Comment by shawroad** [comment]
> BERT-Large, Cased：L=24, H=1024, A=16, 总参数=340M：
> https://storage.googleapis.com/bert_models/2018_10_18/cased_L-12_H-768_A-12.zip
> 
> 英文的bert预训练语料库可以从这里下载

对呀  你语料如果是英文  肯定需要英文的预训练模型。 你下载的预训练模型中包含对应的词表。  你那个链接下载的tensorflow模型。记得转为pytorch版本的

**Comment by LiuChen19960902** [comment]
> 这里的词表是bert自带的呀。 如果你要加载bert的预训练，你肯定也要用配套的词表。

那google在预训练bert时候，vocab.txt是怎么生成的呢

**Comment by shawroad** [comment]
如果你想在预训练好的模型上再训练，可以用Bert提供的词表。如果你想重新训练，那你就可以自己构建个词表。词表的构建常用的两种方法，一种是基于字，基于你当前的语料，生成一个字表，另外一种是基于词，可以用jieba 或者lac分词器对你当前的语料进行分词，然后构建。         
            
                
                    
                            
                                
                            
                            
                                xiaolucxy
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        ---- 回复的原邮件 ***@***.***>发送日期2021年07月07日 17:28 ***@***.***> ***@***.******@***.***>主题Re: [shawroad/NLP_pytorch_project] bert_pretrain里的vocab.txt如何生成 (#30)



这里的词表是bert自带的呀。 如果你要加载bert的预训练，你肯定也要用配套的词表。



那google在预训练bert时候，vocab.txt是怎么生成的呢



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/shawroad/NLP_pytorch_project/issues/30#issuecomment-875446596",

"url": "https://github.com/shawroad/NLP_pytorch_project/issues/30#issuecomment-875446596",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
